// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/home.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    NavHeader: typeof import('./src/components/layout/navHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/sideBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
